name: Changelog

on:
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - uses: actions/checkout@v3
      - uses: zattoo/changelog@v1
        with:
          token: ${{github.token}}
          exclude: .github/**
