name: Integration test master

# This tests that Zepter wont panic on Polkadot-SDK, Substrate, Polkadot or Cumulus.

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  dotsama:
    runs-on: self-hosted
    name: "Check"
    strategy:
      matrix:
        repo: [substrate]

    steps:
    - uses: actions/checkout@master
      name: Clone ${{ matrix.repo }}
      with:
        repository: paritytech/${{ matrix.repo }}
        fetch-depth: 1

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:  
        toolchain: 1.85
    
    - name: Cargo install
      run: cargo install --git ${{ github.server_url }}/${{ github.repository }} zepter --rev $GITHUB_SHA --locked -q
    
      # Substrate master should be green since its using Zepter in its CI.
    - name: Zepter passes
      run: |
        echo "Checking features #1"
        zepter lint propagate-feature --feature try-runtime --left-side-feature-missing=ignore --workspace --fix --feature-enables-dep="try-runtime:frame-try-runtime"
        echo "Checking features #2"
        zepter lint propagate-feature --feature runtime-benchmarks --left-side-feature-missing=ignore --workspace --feature-enables-dep="runtime-benchmarks:frame-benchmarking"
        echo "Checking features #3"
        zepter lint propagate-feature --feature std --left-side-feature-missing=ignore --workspace
        echo "Checking formatting #1"
        zepter format features --check --exit-code-zero
