# Prevents accidential breackage for known downstream projects.

name: Downstream Integration

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches: [ "master" ]
  schedule:
  - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  dotsama:
    runs-on: self-hosted
    name: "Check"
    strategy:
      matrix:
        repo: ["paritytech/polkadot-sdk", "open-web3-stack/open-runtime-module-library"]
        version: [0.13.2, 0.13.3, "*"]

    steps:
    - uses: actions/checkout@master
      name: Clone repo
      with:
        repository: ${{ matrix.repo }}
        fetch-depth: 1
    
    - name: Install
      run: cargo install zepter --version '${{ matrix.version }}' -f --locked -q --no-default-features
    
    - name: Zepter Passes on ${{ matrix.repo }}
      run: |
        zepter run check
        zepter
        git diff --exit-code
