name: Integration test master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  dotsama:
    runs-on: self-hosted
    name: "Check"
    strategy:
      matrix:
        repo: [substrate, polkadot, cumulus]

    steps:
    - uses: actions/checkout@master
      name: Clone ${{ matrix.repo }}
      with:
        name: paritytech/${{ matrix.repo }}
        ref: refs/heads/master
        depth: 1
    - name: Zepter check ${{ matrix.repo }} master
      run: |
        cargo r -r -- lint propagate-feature --feature try-runtime --left-side-feature-missing=ignore --workspace --fix --feature-enables-dep="try-runtime:frame-try-runtime" || true
        cargo r -r -- lint propagate-feature --feature runtime-benchmarks --left-side-feature-missing=ignore --workspace --feature-enables-dep="runtime-benchmarks:frame-benchmarking" || true
        cargo r -r -- lint propagate-feature --feature std --left-side-feature-missing=ignore --workspace || true
