name: Smokescreen

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  install:
    name: "Cargo install"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cargo install
        run: cargo install --path . --locked -q
      
      - name: CLI works
        run: zepter --version && zepter --help

      - name: Cargo install (no-default-features)
        run: cargo install --path . --locked -q --no-default-features

      - name: CLI works (no-default-features)
        run: zepter --version && zepter --help
