name: Smokescreen

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master, dev]
    tags: ["v*.*.*"]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  install:
    name: "Cargo install"
    runs-on: ubuntu-latest

    steps:
      - name: Cargo install
        run: cargo install --git ${{ github.server_url }}/${{ github.repository }} zepter --rev $GITHUB_SHA --locked -q
      
      - name: CLI works
        run: zepter --version && zepter --help
