name: Markdown

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master, dev]
  pull_request:
    types: [review_requested, ready_for_review]

env:
  CARGO_TERM_COLOR: always

jobs:
  linkCheck:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Skip if unchanged
        id: changed-files-specific
        uses: tj-actions/changed-files@v20
        with:
          files: |
            *.md
            *.markdown

      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: "--verbose --cache --max-cache-age 1d ."
          fail: true
