name: Markdown

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "master" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  linkCheck:
    name: "Lint"
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Skip if unchanged
        id: changed-files-specific
        uses: tj-actions/changed-files@v46
        with:
          files: |
            *.md
            *.markdown

      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: "--verbose --cache --max-cache-age 1d . --accept 200,429"
          fail: true
