name: Rust MSRV

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    name: "Check"

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install MSRV
      run: cargo install cargo-msrv --locked -q
    - name: Verify MSRV
      run: cargo msrv verify -- cargo install --locked --path .
